# Auction plugin by SainttX

settings:
  use-shortened-times: false

# General Auction information
auction-start-fee: 0
auction-tax-percentage: 0
default-auction-start-time: 30
delay-between-auctions-seconds: 5
default-bid-increment: 50
minimum-bid-increment: 10
maximum-bid-increment: 100
minimum-auction-start-price: 10
maximum-auction-start-price: 30000

# Enabling and disabling certain features
allow-auctioning-named-items: true
allow-auction-auto-winning: true
allow-creative-auctioning: false
allow-auction-help-command: true
allow-auction-end-command: false
allow-auction-cancel-command: true
allow-using-bid-auto-command: true
allow-damaged-items: true

# Blocking commands
block-commands-when-auctioning: false
block-commands-if-auction-queued: false
blocked-commands:
- "/test"

# Per world Auctioning
disabled-worlds:
- 'testworld'

# Broadcast times
broadcast-times:
- '60'
- '30'
- '10'
- '3'
- '2'
- '1'

# Other
auction-queue-limit: 3
must-cancel-auction-before: 15

# Anti-snipe
# max-per-auction is the max amount of times an auction can have time added
# add-seconds is the amount of time in seconds to add each time the auction is sniped
enable-anti-snipe: true
anti-snipe-max-per-auction: 3
anti-snipe-add-seconds: 5

# Use http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html
banned-items:
- BEDROCK

# If an items lore contains any of the texts here, the item
# won't be allowed to be put into an auction
banned-lore:
- 'A string of lore'